# Site settings
title: Community Health Explorer
baseurl: "/community-health-report" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Prose configuration
prose: 
  rooturl: "_data"
  ignore: ['/css', '/_includes', '/_layouts', '/scripts', '/', '_data/citywide_over_time_labels.yml', '_data/racial_disparity_labels.yml']

# Ruby config for plugins
gems:
  - octopress-paginate

exclude:
- Gemfile
- Gemfile.lock
- vendor
- .travis.yml